config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :teams
  resources :teams_users
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]

  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin', to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  
  
  resources :users do
    member do
      get 'show_teams'
    end
  end
  
  resources :teams do
    member do
      get 'show_members'
      post 'add_members'
      get 'add_members'
      
      get 'show_logs'
      
      get 'show_projects'
      get 'add_projects'
      post 'add_projects'
    end
  end
  
  resources :projects do
    resources 'topics' do
      member do
        post 'show'
        get 'show'
      end
    end
    member do
      get 'show_topics'
      get 'new_topics'
      post 'new_topics'
      
      get 'show_files'
      post 'show_files'
    end
  end
  
  resources :topics do
    
  end
  
  
  
  
  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
    Contact Ruby on Rails Tutorial about the sample app at the
    <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  这里是帮助页面
</p>

app/views/static_pages/home.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="carousel slide" id="carousel-270201">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-270201">
					</li>
					<li data-slide-to="1" data-target="#carousel-270201">
					</li>
					<li data-slide-to="2" data-target="#carousel-270201">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<%= link_to image_tag("home_1.png", alt: "home_1") %>
						<div class="carousel-caption">
							<h4>
								im.tower是tower的山寨版
							</h4>
							<p>
								它是我们的Oracle课程设计大作业
							</p>
						</div>
					</div>
					<div class="item">
						<%= link_to image_tag("home_2.png", alt: "home_2") %>
						<div class="carousel-caption">
							<h4>
								技术选型
							</h4>
							<p>
								后端框架Rails，前端框架Bootstrap，数据库Sqlite3 Oracle Postgre
							</p>
						</div>
					</div>
					<div class="item">
						<%= link_to image_tag("home_3.png", alt: "home_3") %>
						<div class="carousel-caption">
							<h4>
								吉林大学Minecraft团队
							</h4>
							<p>
								马杰，王多民，芦鑫，李想
							</p>
						</div>
					</div>
				</div> <a data-slide="prev" href="#carousel-270201" class="left carousel-control">‹</a> <a data-slide="next" href="#carousel-270201" class="right carousel-control">›</a>
			</div>
		</div>
	</div>
</div>


<div class="center hero-unit">
    <h1> 欢迎使用im.tower</h1> 

		
    <h2>
			简单好用的团队协作工具
    </h2>

    <%= link_to "Sign up for free!", signup_path, class:"btn btn-large btn-primary"%>
</div>

Powered by <%= link_to image_tag("rails.png", alt: "Rails", width: 80, height: 100), 'http://rubyonrails.org/' %>
<%= link_to image_tag("oracle.png", alt:"oracle", width: 80, height: 100), 'http://oracle.com'%>
<%= link_to image_tag("bootstrap.png", alt:"bootstrap", width: 80, height: 100), 'http://getbootstrap.com'%>
<%= link_to image_tag("postgre.png", alt:"postgre", width: 80, height: 100), 'http://postgresql.org'%>