config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :teams
  resources :teams_users
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]

  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin', to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  
  
  resources :users do
    member do
      get 'show_teams'
    end
  end
  
  resources :teams do
    member do
      get 'show_members'
      post 'add_members'
      get 'add_members'
      
      get 'show_logs'
      
      get 'show_projects'
      get 'add_projects'
      post 'add_projects'
    end
  end
  
  resources :projects do
    resources 'topics' do
      member do
        post 'show'
        get 'show'
      end
    end
    member do
      get 'show_topics'
      get 'new_topics'
      post 'new_topics'
      
      get 'show_files'
      post 'show_files'
    end
  end
  
  resources :topics do
    
  end
  
  
  
  
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :teams
  has_many :topics
  has_many :messages
  
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :signed_in_user, only:[:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to im.tower!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else 
      render 'edit'
    end
  end

  def destroy
    User.find_all(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end
  
  def delete_team_relationship
    puts "HFFFF".red
  end
    
  def show_teams
    
    #@team_ids = Teams_User.where(user_id: params[:id])
    #@teams = Team.where(id: @team_ids)
    @user = User.find(params[:id])
    @teams = @user.teams
    
    flash[:success] = "All Teams"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end 

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def correct_user
    @user = User.find(current_user[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 50})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
    def team_relationship_for(user, team)
      @team_user = Teams_User.where(user_id: user.id, team_id: team.id)
    end
    
    def join_team_time_for(user, team)
      @team_user = Teams_User.where(user_id: user.id, team_id: team.id).first
      @team_user.created_at
    end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
        data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
      <% end %>
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

<h1> All users </h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="span6 offset3">
        <%= form_for(@user) do |f| %>
            <%= render 'fields', f: f %>
            <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>

app/views/users/show_teams.html.erb
<% provide(:title, "Team") %>


<div class="teams row">
	<aside class="span3">
		
				
		<section>
			<ul class="thumbnails">
				<% @teams.each do |team| %>
				<li class="span2">
					<div class="thumbnail">
						<%= link_to image_tag("team_icon.png", alt: "team"), team %>
						<h4><%= team.name %></h4>
						<% if team.creator_id == current_user[:id] %>
							<%= link_to "delete", team, method: :delete, data: { confirm: "You sure?" } %>
						<% end %>
					</div>
					
				</li>
				<% end %>
			</ul>
			
			<div class="jumbotron">
				<button class="btn btn-large" type="button"><%= link_to "New Team", new_team_path %></button>
			</div>
			
		</section>
	</aside>
</div>
	