config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users
  resources :teams
  resources :teams_users
  resources :projects
  resources :sessions, only: [:new, :create, :destroy]

  
  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin', to: 'sessions#new',          via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  
  
  resources :users do
    member do
      get 'show_teams'
    end
  end
  
  resources :teams do
    member do
      get 'show_members'
      post 'add_members'
      get 'add_members'
      
      get 'show_logs'
      
      get 'show_projects'
      get 'add_projects'
      post 'add_projects'
    end
  end
  
  resources :projects do
    resources 'topics' do
      member do
        post 'show'
        get 'show'
      end
    end
    member do
      get 'show_topics'
      get 'new_topics'
      post 'new_topics'
      
      get 'show_files'
      post 'show_files'
    end
  end
  
  resources :topics do
    
  end
  
  
  
  
  

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :uploaders
  has_many :topics
  
  validates :name, presence: true
end

app/controllers/projects_controller.rb
require 'carrierwave/orm/activerecord'

class ProjectsController < ApplicationController
  before_action :signed_in_user, only:[:show_topics, :show_files, :show, :index, :edit, :update, :destroy]
  before_action :belong_to_this_project, only:[:show_files, :show, :index, :edit, :update, :destroy]
  
  def show
    @project = Project.find(params[:id])
  end
  
  def show_files
    @project = Project.find(params[:id])
    @uploaders = @project.uploaders
    
    if params[:uploaders]
      u = Uploader.new(project_id: params[:id], user_id: current_user[:id])
      u.file = params[:uploaders][:file]
      u.save!
      flash[:success] = "成功存储 " + u.file.identifier
    end
  end
  
  def show_topics
    @project = Project.find(params[:id])
    @topics = Topic.where(project_id: params[:id])
    
  end
  
  def new_topics
    @project = Project.find(params[:id])
    if params[:topics]
      @topic = Topic.new(user_id: current_user[:id],
                          project_id: params[:id], 
                          name: params[:topics][:name], 
                          content: params[:topics][:content])
      if @topic.save!
        flash[:success] = "成功发帖"
        redirect_to @project
        
      end
    end
  end
    
  def update
    redirect_to root_path
  end
  
  
  private
    
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end 
    
    # 判断用户是否是这个团队中的人，进而判断是否有权利看这个项目
    def belong_to_this_project
      @project = Project.find(params[:id])
      
      if Teams_User.where(user_id: current_user[:id], team_id: @project.team_id).first.nil?
        redirect_to root_path, notice: "你不是这个团队中的人"
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/new_topics.html.erb
<% provide(:title, 'Add new Topic') %>
<h1>New Topic</h1>

<div class="row">
	<div class="span6 offset3">
				
    <%= form_for("topics", controller: "projects", action: "new_topics") do |f| %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.label :content %>
			<%= f.text_area :content %>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
	</div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<ul class="thumbnails">
				<li class="span4">
					<div class="thumbnail">
						
						<%= link_to image_tag("discuss.png", alt: "discuss") %>
						<div class="caption">
							<h3>
								讨论区
							</h3>
							<p>
								沟通是团队和谐的基石
							</p>
							<p>
								
								<%= link_to raw("查看"), 
								          show_topics_project_path, 
								          class: "btn btn-primary",
								          method: :get %>
								
													
							</p>
						</div>
					</div>
				</li>
				<li class="span4">
						<div class="thumbnail">
							<%= link_to image_tag("file.png", alt: "file", width: 220, height: 240) %>
							<div class="caption">
								<h3>
									文件区
								</h3>
								<p>
									大家共享的云存储
								</p>
								<p>
									<%= link_to raw("查看"), 
									          show_files_project_path, 
									          class: "btn btn-primary",
									          method: :get %>
								
								
								</p>
							</div>
						</div>
					</li>
					<li class="span4">
						<div class="thumbnail">
							<%= link_to image_tag("task.png", alt: "task", width: 200, height: 200) %>
							<div class="caption">
								<h3>
									任务列表
								</h3>
								<p>
									将项目分解成独立任务，事半功倍的工作法
								</p>
								<p>
									<%= link_to raw("查看"), 
									          show_members_team_path, 
									          class: "btn btn-primary",
									          method: :get %>
								
								</p>
							</div>
						</div>
					</li>
			</ul>
		</div>
	</div>
</div>

app/views/projects/show_discusses.html.erb
<div class="container">
	<div class="row">
			<div class="span12">
				<div class="page-header">
					<h1>
						讨论区<small>思想的碰撞 <%= link_to raw("发帖"), show_discusses_project_path, class: "btn btn-primary", method: :get %></small>
					</h1>
				</div>
			</div>
		</div>
	
	
	<div class="row">
		<div class="span2">
			<div class="row">
				<div class="span6">
				</div>
				<div class="span6">
				</div>
			</div>
		</div>
		<div class="span6">
			<h2>
				标题
			</h2>
			<p>
				本可视化布局程序在HTML5浏览器上运行更加完美, 能实现自动本地化保存, 即使关闭了网页, 下一次打开仍然能恢复上一次的操作.
			</p>
			<p>
				<a class="btn" href="#">More »</a>
			</p>
		</div>
		<div class="span4">
			 <span class="badge">1</span> <span class="label">文字标签</span>
		</div>
	</div>
	
	<div class="row">
		<div class="span2">
			<div class="row">
				<div class="span6">
				</div>
				<div class="span6">
				</div>
			</div>
		</div>
		<div class="span6">
			<h2>
				标题
			</h2>
			<p>
				本可视化布局程序在HTML5浏览器上运行更加完美, 能实现自动本地化保存, 即使关闭了网页, 下一次打开仍然能恢复上一次的操作.
			</p>
			<p>
				<a class="btn" href="#">More »</a>
			</p>
		</div>
		<div class="span4">
			 <span class="badge">1</span> <span class="label">文字标签</span>
		</div>
	</div>
</div>

app/views/projects/show_files.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<%= form_for "uploaders", :html => {:multipart => true} do |f| %>
			<%= f.file_field :file %>
			<%= f.submit "Upload", class: "btn"%>
			<% end %>
			<%= link_to raw("回到项目"), 
			          @project, 
			          class: "btn btn-primary",
			          method: :get %>
		</div>
	</div>
	<div class="row">
		<% @uploaders.each do |up| %>
		<div class="span3">
			<div class="hero-unit">
				<h1>
					<% if up.file.url.split(".").last == "doc" %>
					<%= link_to image_tag("doc.png", alt: "doc", width: 230, height: 230), up.file.url %>
					<% end %>
					<% if  up.file.url.split(".").last == "pdf" %>
					<%= link_to image_tag("pdf.png", alt: "pdf", width: 230, height: 230), up.file.url %>
					<% end %>
					<% if  up.file.url.split(".").last == "ppt" %>
					<%= link_to image_tag("ppt.png", alt: "ppt", width: 230, height: 230), up.file.url %>
					<% end %>
					
					
				</h1>
				<p>
					<%= up.file.url.split("/").last %>
				</p>			
			</div>		
		</div>
		<% end %>
	</div>
</div>

app/views/projects/show_topics.html.erb
<div class="container">
	<div class="row">
		<div class="span12">
			<div class="page-header">
				<h1>
					讨论区<small>思想的碰撞 <%= link_to raw("发帖"), new_topics_project_path, class: "btn btn-primary", method: :get %></small>
				</h1>
			</div>
		</div>
	</div>
	
	<% @topics.each do |topic| %>
	<div class="row">
		<div class="span2">
			<div class="row">
				<div class="span6">
					<%= gravatar_for topic.user %>
				</div>
				<div class="span6">
					<%= link_to topic.user.name, topic.user %>
				</div>
			</div>
		</div>
		<div class="span6">
			<h2>
				<%= link_to topic.name, project_topic_url(params[:id], topic.id) %>
			</h2>
			<p>
				<%= topic.content %>
			</p>
			
		</div>
		<div class="span4">
			<span class="badge"><%= topic.messages.size %></span> <span class="label"><%= topic.created_at %></span>
		</div>
	</div>
	<% end %>
	
	<%= link_to raw("回到项目"), 
	          @project, 
	          class: "btn btn-primary",
	          method: :get %>
	
	
</div>